export const words = [
  "libro", "silla", "ordenador", "casa", "perro", "gato", "papel", "lapiz", "mesa", "telefono",
  "sol", "llave", "tren", "avion", "cafe", "leche", "manzana", "ventana", "puerta", "agua",
  "planta", "ciudad", "playa", "musica", "cielo", "pared", "pelota", "juego", "azul", "verde",
  "amarillo", "rojo", "blanco", "negro", "gris", "feliz", "triste", "enojado", "contento", "nuevo",
  "viejo", "bueno", "malo", "rapido", "lento", "alto", "bajo", "frio", "caliente", "fuerte",
  "debil", "largo", "corto", "dulce", "amargo", "salado", "simple", "complejo", "claro", "oscuro",
  "grande", "pequeno", "delgado", "gordo", "amigo", "enemigo", "hermoso", "feo", "tranquilo",
  "ruidoso", "serio", "gracioso", "facil", "dificil", "libre", "ocupado", "rico", "pobre",
  "interesante", "aburrido", "calmado", "furioso", "joven", "moderno", "antiguo",
  "hombre", "mujer", "nino", "nina", "persona", "familia", "amor", "odio", "amistad", "enemistad",
  "vida", "muerte", "trabajo", "estudio", "dinero", "exito", "fracaso", "sueno", "realidad",
  "pasado", "presente", "futuro", "lugar", "tiempo", "forma", "modo", "causa", "efecto",
  "razon", "motivo", "accion", "reaccion", "sistema", "metodo", "idea", "pensamiento", "palabra",
  "texto", "mensaje", "imagen", "sonido", "voz", "movimiento", "cambio", "progreso", "desarrollo",
  "numero", "cantidad", "tamano", "peso", "altura", "ancho", "profundidad", "luz", "sombra",
  "aire", "fuego", "agua", "tierra", "planta", "animal", "humano", "naturaleza", "universo",
  "ciencia", "tecnologia", "arte", "cultura", "religion", "politica", "economia", "sociedad", "historia",
  "geografia", "educacion", "salud", "felicidad", "tristeza", "ira", "alegria", "esperanza", "desesperacion",
  "placer", "dolor", "belleza", "fealdad", "paz", "guerra", "amabilidad", "maldad", "virtud",
  "vicio", "luz", "oscuridad", "calor", "frio", "vida", "muerte", "inicio", "fin", "accion",
  "reaccion", "bien", "mal", "creacion", "destruccion", "orden", "caos", "riqueza", "pobreza",
  "exito", "fracaso", "sabiduria", "ignorancia", "verdad", "mentira", "pasion", "indiferencia", "movimiento",
  "quietud", "certeza", "duda", "conocimiento", "ilusion", "desdicha", "union", "separacion", "compania",
  "soledad", "fortaleza", "dia", "noche", "luna", "estrella", "mar", "montana", "rio",
  "arroyo", "lago", "flor", "arbol", "hierba", "arena", "roca", "piedra", "metal",
  "plastico", "madera", "vidrio", "viento", "nube", "nieve", "helado", "templado", "anaranjado",
  "rosado", "violeta", "y", "o", "pero", "porque", "si", "cuando", "aunque", "mientras"
];
